### ISSUE TITLE
Example Pokemon Battles

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/pokemonbattlelib#12]
We need test cases to ensure the accuracy of our Pokemon battle implementation.

Eventually, we will turn these into automated test cases.

### Tasks

- [ ] Describe 3 Pokemon battles from start to finish, clearly documenting the results for each turn with the reason for why it happened, and put it in the documentation (`docs/example-battles.md`)
    - If possible, include the RNG seed at the start of the battle, damage numbers, buffs, debuffs, etc. The more information the better.
    - [ ] One battle should be as simple as possible, avoiding edge cases, between 2 low level Pokemon (one on each side).
    - [ ] One battle should include super-effective/not-very-effective type matchups.
    - [ ] The complexity of the last battle is up to your discretion.

**Comment by ronduma** [comment]
[low-level-battle.txt](https://github.com/StevensSEC/pokemonbattlelib/files/5985593/low-level-battle.txt)

**Comment by dyc3** [comment]
Unassigning due to inactivity.

**Comment by dyc3** [comment]
This is no longer relevant to the current state of the project.
