### ISSUE TITLE
Enforce gofmt in CI

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/pokemonbattlelib#32]
For some reason, some people's editors are not automatically running `gofmt` on the code. This causes erroneous changes to be made when somebody's editor _does_ auto run `gofmt`, and it clogs up diffs when reviewing pull requests.

### Tasks

- [x] Have CI test to make sure gofmt won't modify any files
    - [ ] Maybe auto commit corrections?
    - `test -z $(gofmt -l . | tr -d '\n')` returns non-zero exit code if this test fails
- [x] Have codegen script run gofmt on generated code
