### ISSUE TITLE
Data entry and accessing it at runtime

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/pokemonbattlelib#5]
We need to be able to access metadata about pokemon, moves, etc at runtime. `pokedex.go` should manage this information.

### Desired Solution

Code generation based on files. When `go build` is run, it should run a script to generate the code with the metadata. This is accomplished with the magic comment `go:generate`.

This example will run `gen.go` before building the rest of the package.
```go
//go:generate go run gen.go
```

The script should read some files out of the `data/` directory, and generate code based on it's contents.

### Tasks

- [x] File format(s) or schemas for metadata
- [x] API for accessing metadata
- [x] Script for generating code
- [x] Data entry
    - [x] Pokemon
    - [x] Moves

**Comment by rafaelbreno** [comment]
May I help?

**Comment by dyc3** [comment]
I don't see why not, @rafaelbreno . I'll assign you.

**Comment by dyc3** [comment]
Hey @rafaelbreno, it's been a while. Are you running into any issues? Do you still want the issue?
