### ISSUE TITLE
Add RNG Interface

### ISSUE THREAD

**Issue by carpenterd777** [StevensSEC/pokemonbattlelib#9]
We need an interface to handle random number generators. More specifically, we need an interface that we can use to implement various RNG algorithms used in Pokemon games. See: https://github.com/StevensSEC/pokemonbattlelib/wiki/Requirements#rng

For the initial seed, since getting the delay between the player starting the game and pressing "Continue", we can probably ignore it.

### Tasks

- [ ] Create an interface type to handle setting the seed and generating random numbers between 2 values (inclusive)
- [ ] Implement this interface on a new type which implements the LCRNG described [here](https://github.com/StevensSEC/pokemonbattlelib/wiki/Requirements#rng).
  - [ ] Allow setting the seed
  - [ ] Generate seed
    - [ ] Get the date and time
